// This file is automatically generated and contains assets from oasys.
// Generate for other networks by running: yarn generate-assets [network].
// Supported networks are: arbitrum, goerli, mainnet, and polygon.

import { Address } from '@graphprotocol/graph-ts';

class Assets {
  public stableAssets: Address[];
  public pricingAssets: Address[];
  public fxAssets: Address[];
  public fxAggregators: Address[];
}

export const USDC_ADDRESS = Address.fromString('0x4D17C0609B77e456Fb98Ea99a62bCeF09adae32D');

export const assets: Assets = {
  stableAssets: [
    Address.fromString('0x4D17C0609B77e456Fb98Ea99a62bCeF09adae32D'), // USDC
  ],
  pricingAssets: [
    Address.fromString('0x5200000000000000000000000000000000000001'), // OAS
    Address.fromString('0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000'), // OAS
    Address.fromString('0xdd30c42D57a0f14DD44c809F59836D57392FDbC9'), // WBTC
    Address.fromString('0x5801E5a61164024Be2554248E33127c6ebC8C113'), // WETH
    Address.fromString('0x5B1CC635E524cAbb63a581c050C895534755F297'), // MCHC
    Address.fromString('0xddb07cc0f2f9fb7899dba5a21964f3c6d2740e44'), // TCGC
  ],
  fxAssets: [
  ],
  fxAggregators: [
  ],
};
